/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PlanetModal: typeof import('./components/planetModal.vue')['default']
    PlanetRender: typeof import('./components/planetRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeJsComponent: typeof import('./components/threeJsComponent.vue')['default']
  }
}
